FROM node:10-alpine

RUN mkdir -p /var/www/ateliernobre/node_modules && chown -R node:node /var/www/ateliernobre

WORKDIR /var/www/ateliernobre

COPY package*.json ./

USER node

RUN npm install

COPY --chown=node:node . .

EXPOSE 8080

CMD [ "node", "server.js" ]