version: '3'

services:
hnl-angular-ateliernobe-app:
image: nobrehnl/hnl_company:hnl-angular-ateliernobre-app-v1.0.0.003
container_name: hnl-angular-ateliernobre-app
environment:
VIRTUAL_HOST: ateliernobre.com.br
VIRTUAL_PORT: 4002
restart: on-failure
ports:
- "4002:8080"

networks:
default:
external:
name: nginx-proxy